### ISSUE TITLE
Bücher addieren

### ISSUE THREAD

**Issue by cnoss** [cnoss/home#38]
Bitte hier mal folgende Bücher addieren:
https://github.com/cnoss/home/tree/master/_books

Bitte prüfen, ob die Bücher als Papierversion oder Online Version oder beides vorhanden sind:
["Online Ressource", "Printversion", "Online Ressource & Printversion"]

Bücher:
  <li>Tanja Wehr, Die Sketchnote Starthilfe. Neue Bilderwelten (2018), mitp-Verlag, Frechen <a href="https://content-select.com/de/portal/media/view/5c858640-3164-4fa8-b3c8-6037b0dd2d03?forceauth=1">E-Book via vpn</a></li>
  <li>Eva-Lotta Lamm, Sketchnotes einer Weltreise (2017), mitp-Verlag, Frechen <a href="https://content-select.com/de/portal/media/view/5c858640-d3c4-4f1d-91e1-6037b0dd2d03?forceauth=1">E-Book via vpn</a></li>
  <li>Mike Rohde, Das Sketchnote Handbuch (2014), mitp-Verlag, Frechen <a href="https://content-select.com/de/portal/media/view/5c858641-5294-406d-9fc7-6037b0dd2d03?forceauth=1">E-Book via vpn</a></li>
  <li>Temple Grandin P. Visual Thinking, The Hidden Gifts of People Who Think in Pictures, Patterns, and Abstractions. Riverhead Books; 2022 <a href="https://search.ebscohost.com/login.aspx?direct=true&amp;db=nlebk&amp;AN=3141506&amp;site=ehost-live&amp;ebv=EK&amp;ppid=Page-__-1">E-Book via vpn</a></li>

  <li><a href="http://www.digibib.net/permalink/832/FHBK-x/HBZ:TT050418640">Informationsvisualisierung: Web - Print - Signaletik. Erfolgreiches Informationsdesign: Leitsysteme, Wissensvermittlung und Informationsarchitektur / Torsten Stapelkamp</a></li>
  <li><a href="http://www.digibib.net/permalink/832/FHBK-x/HBZ:TT050392166">Interaction- und Interfacedesign: Web-, Game-, Produkt- und Servicedesign Usability und Interface als Corporate Identity / Torsten Stapelkamp</a></li>
  <li><a href="http://www.digibib.net/permalink/832/FHBK-x/HBZ:TT050419679">Kompendium der visuellen Information und Kommunikation / Kerstin Alexander</a></li>
  <li><a href="http://www.digibib.net/permalink/832/FHBK-x/HBZ:HT015123236">Simplicity: die zehn Gesetze der Einfachheit / John Maeda</a></li>
  <li><a href="https://link.springer.com/chapter/10.1007%2F978-3-662-53918-7_3">Webdesign: Screendesign / Peter Bühler, Patrick Schlaich, Dominik Sinner</a></li>
  <li><a href="https://www.degruyter.com/document/doi/10.1515/9783035625073/html">Visualizing complexity: Handbuch modulares Informationsdesign / Darjan Hil und Nicole Lachenmeier</a></li>
  <li><a href="https://content-select.com/de/portal/media/view/5f4a4d25-f458-43bb-a3a6-0ee6b0dd2d03?forceauth=1">Laws of UX: 10 praktische Grundprinzipien für intuitives, menschenzentriertes UX-Design / Yablonski, Jon ; Kommer, Christoph</a></li>

Im Bib Katalog bitte mal suchen:
- [Design systems: a practical guide to creating design languages for digital products.](https://thb-koeln.digibib.net/search/katalog/record/(DE-605)HT019479321?be-katalog-sort=relevance&q-al=kholmatova&start=1&count=20&hitcount=1&pos=1)
- Atomic design – https://thb-koeln.digibib.net/search/katalog/record/(DE-605)HT019637264?be-katalog-sort=relevance&q-al=atomic+design&start=1&count=20&hitcount=6&pos=1

**Comment by cnoss** [comment]
[Detailansicht für Treffer 2 öffnen](https://thb-koeln.digibib.net/search/katalog/record/(DE-605)HT018972709?be-katalog-sort=relevance&q-al=multiscreen&start=1&count=20&hitcount=4&pos=2)
[Multiscreen UX design: developing for a multitude of devices](https://thb-koeln.digibib.net/search/katalog/record/(DE-605)HT018972709?be-katalog-sort=relevance&q-al=multiscreen&start=1&count=20&hitcount=4&pos=2)

**Comment by cnoss** [comment]
@calvinhnzr Aloha, wie sieht es denn hier aus?

**Comment by calvinhnzr** [comment]
@cnoss Hallo, ich habe soeben einen neuen Branch (books) mit den mit Büchern dem Repo hinzugefügt. Leider konnte ich die Änderungen nicht testen, da eine package.json zum lokalen ausführen der Website fehlte. Hoffe alles hat soweit geklappt!

**Comment by cnoss** [comment]
@calvinhnzr könntest Du bitte noch Bilder von den Covern dazu pflegen?

**Comment by calvinhnzr** [comment]
@noss Habe soeben die Cover im Branch ergänzt. Hoffe es reicht aus die Dateinamen der Bilder den .md Files entsprechend anzupassen. :D Konnte sonst keine anderen Hinweise finden, da ich es lokal nicht testen konnte.
